---
language: ruby
cache: bundler
script: "bundle exec rake test"
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - ruby-head
  - jruby
  - truffleruby
  - rbx

notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 1.9
    - rvm: 2.0
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: ruby-head
    - rvm: jruby
    - rmv: truffleruby
    - rvm: rbx
  fast_finish: true
  include:
    - rvm: jruby-19mode: # JRuby in 1.9 mode
      before_install:
        - gem install bundler -v 2.3.26

bundler_args: --without code_quality
