name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby-version:
          - head
          - ruby
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - jruby
          - jruby-head
          - truffleruby
          - truffleruby-head
          - truffleruby+graalvm
        include:
          - os: windows-latest
            ruby-version: head
          - os: windows-latest
            ruby-version: '3.4'
          - os: windows-latest
            ruby-version: mingw
          - os: windows-latest
            ruby-version: mswin
          - os: windows-latest
            ruby-version: ucrt
          - os: macos-latest
            ruby-version: 'head'
          - os: macos-latest
            ruby-version: '3.4'
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby-version, 'head') }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - name: Add fiddle to bundle on Windows
      if: runner.os == 'Windows'
      run: |
        bundle add fiddle --skip-install --quiet
        bundle install --jobs 3 --retry 3
    - name: Run tests
      run: bundle exec rake test
    - name: Read coverage
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.ruby-version == 'ruby' }}
      run: |
        ruby -rjson -e '
          coverage = JSON.parse(File.read("coverage/.last_run.json")).dig("result", "line")
          abort "coverage result not found" unless coverage

          File.open(ENV.fetch("GITHUB_ENV"), "a") do |env|
            env.puts "COVERAGE=#{format("%.2f", coverage)}"
          end
        '
    - name: Update coverage badge
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.ruby-version == 'ruby' }}
      uses: Schneegans/dynamic-badges-action@v1.8.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 70532e48ae064176aaded5fbbdbf2ffc
        filename: highline-coverage.json
        label: coverage
        message: ${{ env.COVERAGE }}%
        valColorRange: ${{ env.COVERAGE }}
        maxColorRange: 100
        minColorRange: 0
